export const ADD_TO_CART_LOADING = 'ADD_TO_CART_LOADING';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED';


export const REMOVE_TO_CART_LOADING = 'REMOVE_TO_CART_LOADING';
export const REMOVE_TO_CART_SUCCESS = 'REMOVE_TO_CART_SUCCESS';
export const REMOVE_TO_CART_FAILED = 'REMOVE_TO_CART_FAILED';
